name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install libboost-program-options-dev
      run: apt install -y libboost-program-options-dev
    - name: make build dir
      run: mkdir build
    - name: run cmake
      working-directory: build
      run: cmake ..
    - name: configure
      working-directory: build
      run: ./configure
    - name: make all
      working-directory: build
      run: make all
    - name: make check
      working-directory: build
      run: make check
    - name: make distcheck
      working-directory: build
      run: make distcheck
