name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: ls
      run: ls
    - name: make build dir
      run: mkdir build
    - name: cd build dir
      run: cd build
    - name: run cmake
      run: cmake ..
    - name: configure
      run: ./configure
    - name: make all
      run: make all
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
