name: C/C++ Ubuntu Build

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install libboost
      run: sudo apt-get install -y libboost-program-options-dev libboost-system-dev
    - name: create build dir
      run: mkdir build
    - name: run cmake
      working-directory: build
      timeout-minutes: 3
      run: cmake ..
    - name: make tcp
      working-directory: build
      continue-on-error: true
      run: make tcp
    - name: make echoserver
      working-directory: build
      continue-on-error: true
      run: make echoserver
    - name: make echoclient
      working-directory: build
      continue-on-error: true
      run: make echoclient
